# Generated by Django 4.0.6 on 2022-07-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.IntegerField()),
                ('pontuacao_dardos', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('pontuacao_metros_rasos', models.DecimalField(decimal_places=3, default=None, max_digits=10)),
                ('modelo_competicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Competicoes.competicao')),
            ],
        ),
    ]
